import './globals.css'
import { Noto_Sans_Arabic } from 'next/font/google'

const inter = Noto_Sans_Arabic({ subsets: ['arabic'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
